Repository dylanpiera/Hallowspeak, pull requests merged in 2019-09, with the labels that each got.

#3 Bulk import
  Hallowspeak/Pages/Lexicon.razor
Labels: New Feature

#5 Add Mobile Styling
  Hallowspeak/Pages/Lexicon.razor
  Hallowspeak/wwwroot/css/site.css
Labels: Style, enhancement

#8 Feature/styling
  Hallowspeak/wwwroot/css/font/Perpetua.eot
  Hallowspeak/wwwroot/css/font/Perpetua.svg
  Hallowspeak/wwwroot/css/font/Perpetua.ttf
  Hallowspeak/wwwroot/css/font/Perpetua.woff
  Hallowspeak/wwwroot/css/site.css
Labels: enhancement
